#!/usr/bin/env bash
# init.sh — reset a sandbox to a pristine, launch-ready state.
#
# Layout (production-faithful consumer layout):
#
#   test/<name>/              <- fresh consumer git repo (git init)
#   └── .agents/              <- git SUBMODULE -> this harness repo @ committed HEAD
#       ├── lint/rules.yaml   <- governance rules (single source of truth)
#       └── skills/           <- sandbox-init, lint, ... skills
#
# The submodule pins the harness at the CURRENT COMMITTED HEAD: the consumer
# repo's history records WHICH harness commit a sandbox was built against.
# Git refuses a submodule URL equal to the superproject, so the submodule
# points at a sibling BARE MIRROR (../mythic-quest-mirror.git) that this
# script creates and refreshes from harness HEAD first.
#
# Guarantees (idempotent — safe to run repeatedly):
#   1. Refuses to wipe a sandbox held by a live opencode session (zombie
#      contamination guard — a stale session keeps writing into the rebuilt
#      sandbox).
#   2. Sandbox wiped completely (disposable by contract) then rebuilt.
#   3. .agents submodule pinned to the CURRENT COMMITTED harness HEAD.
#      Uncommitted harness changes are EXCLUDED (commit first — that is the
#      reproducibility point).
#   4. Fresh consumer git repo; its first commit pins the harness SHA.
#   5. bd ledger initialized (bd init --quiet --stealth) and AGENTS.md
#      generated by `bd setup opencode`.
#   6. Fail-loud verification; exit 1 with a reason if anything is off.
#   7. Commits nothing to the harness repo itself.
#
# Usage: init.sh [sandbox-name]
#   sandbox-name defaults to "benchmark"; lives under test/ (gitignored).
# Exit codes: 0 = ready, 1 = verification failed
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
SANDBOX_NAME="${1:-benchmark}"

fail() { printf 'init.sh: %s\n' "$1" >&2; exit 1; }

# Validate sandbox name: simple alphanumeric/hyphen/underscore, no slashes/dots
if [ -z "$SANDBOX_NAME" ] || echo "$SANDBOX_NAME" | grep -qE '[./]|^$'; then
  fail "sandbox name must be a simple name (alphanumeric/hyphen/underscore, no dots or slashes), got: $SANDBOX_NAME"
fi

SANDBOX="$REPO_ROOT/test/$SANDBOX_NAME"
cd "$REPO_ROOT"
command rm -f .beads.gate.lock 2>/dev/null || true

# 1. Refuse to wipe a sandbox with a live session in it ----------------------
if [ -d "$SANDBOX" ]; then
  LIVE_SESSIONS=$(pgrep -x opencode 2>/dev/null | while read -r pid; do
    CWD=$(lsof -a -p "$pid" -d cwd -Fn 2>/dev/null | sed -n 's/^n//p')
    if [ "$CWD" = "$SANDBOX" ] || [[ "$CWD" == "$SANDBOX"/* ]]; then
      echo "$pid"
    fi
  done || true)
  [ -z "$LIVE_SESSIONS" ] ||
    fail "live opencode session(s) [$LIVE_SESSIONS] hold the sandbox — stop them before wiping ($SANDBOX is disposable but they will corrupt the rebuilt state)"
fi

# 2. Mirror maintenance — submodule remote is a bare clone of this repo ------
MIRROR="$REPO_ROOT/../mythic-quest-mirror.git"
if [ -d "$MIRROR" ]; then
  # '+' forces: the mirror is disposable and must track HEAD even across
  # history rewrites; a plain fetch wedges future runs on stale refs.
  git --git-dir="$MIRROR" fetch -q "$REPO_ROOT" "+refs/heads/*:refs/heads/*" ||
    fail "mirror fetch failed — check $MIRROR"
else
  # --no-local: the worktree has ignored dirs that break local clones
  git clone --bare --no-local -q "$REPO_ROOT" "$MIRROR" ||
    fail "could not create bare mirror at $MIRROR"
fi

HEAD_SHA=$(git rev-parse HEAD) ||
  fail "harness HEAD unreadable — unbalanced repo state?"
[ -n "$(git ls-files .agents)" ] ||
  fail "harness has no committed .agents tree — commit first (the submodule pins COMMITTED state)"

# 3. Wipe and rebuild the sandbox ---------------------------------------------
command rm -rf "$SANDBOX"
mkdir -p "$SANDBOX"

# 4. Consumer repo + .agents submodule at harness HEAD -----------------------
git -C "$SANDBOX" init -q
git -C "$SANDBOX" -c protocol.file.allow=always \
  submodule add -q --name agents "$MIRROR" .agents ||
  fail "submodule add failed (mirror: $MIRROR)"
git -C "$SANDBOX/.agents" checkout -q "$HEAD_SHA" ||
  fail "submodule checkout of $HEAD_SHA failed"
git -C "$SANDBOX" add .agents
git -C "$SANDBOX" -c user.name=harness -c user.email=harness@local \
  commit -qm "chore: pin harness @ ${HEAD_SHA:0:8} (.agents submodule)"

# 5. Seed the sandbox ledger and AGENTS.md ------------------------------------
(cd "$SANDBOX" && bd init --quiet --stealth) >/dev/null 2>&1 ||
  fail "bd init failed in sandbox (is bd on PATH?)"
[ -d "$SANDBOX/.beads" ] || fail "sandbox .beads/ missing after bd init"

(cd "$SANDBOX" && bd setup opencode) >/dev/null 2>&1 ||
  fail "bd setup opencode failed in sandbox (is bd on PATH?)"
[ -f "$SANDBOX/AGENTS.md" ] || fail "sandbox AGENTS.md missing after bd setup"
git -C "$SANDBOX" add AGENTS.md .beads 2>/dev/null || true
git -C "$SANDBOX" -c user.name=harness -c user.email=harness@local \
  commit -qm "chore: bd ledger + managed AGENTS.md" >/dev/null 2>&1 || true

# 6. Fail-loud verification ---------------------------------------------------
AGENTS_TREE="$SANDBOX/.agents"
[ -d "$AGENTS_TREE/lint" ] && [ -d "$AGENTS_TREE/skills" ] ||
  fail "submodule checkout incomplete ($AGENTS_TREE/lint|skills missing)"
[ "$(git -C "$AGENTS_TREE" rev-parse HEAD)" = "$HEAD_SHA" ] ||
  fail "submodule HEAD drifted from harness HEAD"
[ -f "$AGENTS_TREE/lint/rules.yaml" ] ||
  fail "governance rules missing in submodule: lint/rules.yaml"
git -C "$SANDBOX" status --porcelain | grep -q . &&
  fail "unexpected dirty files in sandbox"

printf 'READY: %s | harness @ %s | git initialized | ledger seeded\n' \
  "$SANDBOX" "${HEAD_SHA:0:8}"
printf 'next: cd %s && opencode (game-build session)\n' "$SANDBOX"
